# pandas

### Partie 1

Installer et importer pandas et numpy et afficher leur versions

In [1]:
!pip3 install pandas
!pip3 install numpy
import pandas as pd
import numpy as np
import random
print("pandas version {}".format(pd.__version__))
print("numpy  version {}".format(np.__version__))

Collecting pandas
  Using cached pandas-1.1.4-cp38-cp38-macosx_10_9_x86_64.whl (10.1 MB)
Collecting pytz>=2017.2
  Using cached pytz-2020.4-py2.py3-none-any.whl (509 kB)
Collecting numpy>=1.15.4
  Using cached numpy-1.19.4-cp38-cp38-macosx_10_9_x86_64.whl (15.3 MB)
Requirement already satisfied: python-dateutil>=2.7.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Installing collected packages: pytz, numpy, pandas
Successfully installed numpy-1.19.4 pandas-1.1.4 pytz-2020.4
WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (1.19.4)
WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.
pandas version 1.1.4
numpy  version 1.19.4

Transformer ces variables en Pandas Series

In [2]:
liste = list(range(0, 17))
dictionary = {"A":  0, "B":1, "C":2, "D":3, "E":5}
liste_series = pd.Series(liste)
liste_series = pd.Series(item for item in liste)
liste_series
dictionary_series = pd.Series(dictionary)
dictionary_series

A    0
B    1
C    2
D    3
E    5
dtype: int64

 - Afficher la variable dictionnaire
 - Transformer le dictionnaire en dataframe

In [3]:
dictionaire = {x:np.random.randint(0,100,50) for x in "ABCDE"}
print(dictionaire)
df_dict=pd.DataFrame.from_dict(dictionaire)
df_dict

{'A': array([85, 13, 32, 75, 55, 56, 15, 28, 33,  7, 78, 23, 61, 88,  7, 67, 89,
       68, 31, 23, 38, 81, 81,  6, 81, 79, 38, 29,  9,  8, 90, 97, 15, 76,
       27, 33, 60, 92, 26,  5, 35, 48, 37, 22, 29,  2,  5, 24, 45, 70]), 'B': array([34, 40, 61, 93, 17, 37, 23, 79, 34, 14, 99, 18, 34, 94, 37, 40, 54,
       54, 94, 34, 48, 25, 86, 71, 62, 22, 44, 39, 62, 66, 87, 25, 44, 75,
       58, 41, 69, 17, 11, 83, 13, 13, 39,  6, 54, 77, 15, 18,  2, 24]), 'C': array([49, 87, 18, 14, 97,  7, 89, 86, 93, 51, 97, 50, 16, 20, 75, 67, 56,
       53, 56, 29, 15, 60, 16, 21, 83, 11, 61, 81, 35, 49,  5, 85, 57, 32,
       59,  5, 69, 48, 22, 87,  6, 14, 33, 93, 85, 20, 68, 33, 99, 95]), 'D': array([64, 25, 91, 16, 58, 95, 16, 22, 41, 95, 94, 54,  7, 13, 46,  9, 94,
       14, 82, 70, 88, 42, 67, 46, 48, 56, 65,  1,  1, 37, 25, 19, 77, 59,
       20, 53, 90, 23, 48, 85, 99, 73, 30, 37, 22, 83, 74, 98, 31, 76]), 'E': array([17, 19,  7, 83, 38, 72, 59, 59, 12, 99, 66, 21, 80, 57, 88, 69, 50,
       16, 74,  3, 67, 50, 13, 88, 53, 55, 60, 24,  1, 44, 56, 32, 99, 76,
       19, 62, 88, 64, 59, 21, 84, 73, 64, 34,  4, 68, 52, 54, 71, 22])}

     A   B   C   D   E
0   85  34  49  64  17
1   13  40  87  25  19
2   32  61  18  91   7
3   75  93  14  16  83
4   55  17  97  58  38
5   56  37   7  95  72
6   15  23  89  16  59
7   28  79  86  22  59
8   33  34  93  41  12
9    7  14  51  95  99
10  78  99  97  94  66
11  23  18  50  54  21
12  61  34  16   7  80
13  88  94  20  13  57
14   7  37  75  46  88
15  67  40  67   9  69
16  89  54  56  94  50
17  68  54  53  14  16
18  31  94  56  82  74
19  23  34  29  70   3
20  38  48  15  88  67
21  81  25  60  42  50
22  81  86  16  67  13
23   6  71  21  46  88
24  81  62  83  48  53
25  79  22  11  56  55
26  38  44  61  65  60
27  29  39  81   1  24
28   9  62  35   1   1
29   8  66  49  37  44
30  90  87   5  25  56
31  97  25  85  19  32
32  15  44  57  77  99
33  76  75  32  59  76
34  27  58  59  20  19
35  33  41   5  53  62
36  60  69  69  90  88
37  92  17  48  23  64
38  26  11  22  48  59
39   5  83  87  85  21
40  35  13   6  99  84
41  48  13  14  73  73
42  37  39  33  30  64
43  22   6  93  37  34
44  29  54  85  22   4
45   2  77  20  83  68
46   5  15  68  74  52
47  24  18  33  98  54
48  45   2  99  31  71
49  70  24  95  76  22

Trouver comment  afficher un descriptif de ce dataframe

In [4]:
df_dict.describe()

               A          B         C          D          E
count  50.000000  50.000000  50.00000  50.000000  50.000000
mean   44.440000  45.720000  51.14000  51.580000  50.920000
std    29.254799  26.870848  30.66342  30.099217  27.347977
min     2.000000   2.000000   5.00000   1.000000   1.000000
25%    23.000000  23.250000  20.25000  23.500000  22.500000
50%    36.000000  40.000000  52.00000  50.500000  56.500000
75%    73.750000  65.000000  82.50000  76.750000  70.500000
max    97.000000  99.000000  99.00000  99.000000  99.000000

Afficher le nombre de fois que chacune des valeurs apparait dans chaque colonne

In [5]:
duplicates = [ [i,df_dict[i].value_counts().sort_values()] for i in df_dict]
duplicates

[['A',
  2     1
  90    1
  89    1
  61    1
  60    1
  56    1
  55    1
  45    1
  92    1
  48    1
  26    1
  97    1
  37    1
  35    1
  32    1
  31    1
  24    1
  28    1
  75    1
  27    1
  79    1
  68    1
  22    1
  67    1
  78    1
  13    1
  70    1
  85    1
  88    1
  9     1
  8     1
  6     1
  76    1
  38    2
  15    2
  7     2
  29    2
  5     2
  33    2
  23    2
  81    3
  Name: A, dtype: int64],
 ['B',
  22    1
  75    1
  58    1
  14    1
  79    1
  48    1
  41    1
  87    1
  83    1
  23    1
  24    1
  61    1
  93    1
  77    1
  99    1
  86    1
  11    1
  66    1
  71    1
  6     1
  69    1
  2     1
  15    1
  62    2
  39    2
  13    2
  17    2
  94    2
  37    2
  25    2
  40    2
  44    2
  18    2
  54    3
  34    4
  Name: B, dtype: int64],
 ['C',
  7     1
  68    1
  83    1
  89    1
  21    1
  86    1
  60    1
  95    1
  6     1
  32    1
  11    1
  69    1
  48    1
  50    1
  51    1
  53    1
  57    1
  35    1
  59    1
  67    1
  22    1
  99    1
  75    1
  81    1
  18    1
  15    1
  61    1
  29    1
  56    2
  87    2
  85    2
  49    2
  16    2
  33    2
  20    2
  14    2
  97    2
  93    2
  5     2
  Name: C, dtype: int64],
 ['D',
  70    1
  65    1
  19    1
  88    1
  85    1
  23    1
  59    1
  90    1
  91    1
  98    1
  99    1
  83    1
  41    1
  42    1
  53    1
  54    1
  31    1
  56    1
  67    1
  58    1
  64    1
  9     1
  7     1
  82    1
  30    1
  77    1
  14    1
  13    1
  20    1
  76    1
  73    1
  74    1
  95    2
  94    2
  1     2
  46    2
  48    2
  16    2
  25    2
  22    2
  37    2
  Name: D, dtype: int64],
 ['E',
  1     1
  84    1
  38    1
  62    1
  60    1
  57    1
  56    1
  55    1
  54    1
  53    1
  52    1
  76    1
  22    1
  68    1
  44    1
  71    1
  83    1
  34    1
  16    1
  32    1
  24    1
  3     1
  12    1
  67    1
  66    1
  80    1
  13    1
  17    1
  74    1
  72    1
  7     1
  69    1
  4     1
  73    1
  50    2
  99    2
  19    2
  21    2
  64    2
  88    3
  59    3
  Name: E, dtype: int64]]

In [39]:
df_dict['B'].value_counts()

34    4
54    3
62    2
39    2
13    2
17    2
18    2
94    2
37    2
25    2
40    2
44    2
2     1
69    1
6     1
71    1
15    1
22    1
87    1
75    1
58    1
14    1
79    1
48    1
41    1
83    1
86    1
23    1
24    1
61    1
93    1
77    1
99    1
11    1
66    1
Name: B, dtype: int64

Afficher uniquement les valeurs surperieures à 30 de la colonne b

In [6]:
df_dict[df_dict.B > 30]

     A   B   C   D   E
0   85  34  49  64  17
1   13  40  87  25  19
2   32  61  18  91   7
3   75  93  14  16  83
5   56  37   7  95  72
7   28  79  86  22  59
8   33  34  93  41  12
10  78  99  97  94  66
12  61  34  16   7  80
13  88  94  20  13  57
14   7  37  75  46  88
15  67  40  67   9  69
16  89  54  56  94  50
17  68  54  53  14  16
18  31  94  56  82  74
19  23  34  29  70   3
20  38  48  15  88  67
22  81  86  16  67  13
23   6  71  21  46  88
24  81  62  83  48  53
26  38  44  61  65  60
27  29  39  81   1  24
28   9  62  35   1   1
29   8  66  49  37  44
30  90  87   5  25  56
32  15  44  57  77  99
33  76  75  32  59  76
34  27  58  59  20  19
35  33  41   5  53  62
36  60  69  69  90  88
39   5  83  87  85  21
42  37  39  33  30  64
44  29  54  85  22   4
45   2  77  20  83  68

Tranformer ces deux listes en series et nommez-les series1 et series2 :
 - Multipliez-les entre elle pour faire une troisième series
 - Combinez-les pour en faire un dataframe

In [7]:
liste1 = list(range(0, 14))
liste2 = list(range(10, 24))
#series1 = pd.Series(liste1, name="S1")
series1 = pd.Series(liste1)
series2 = pd.Series(liste2)
s3 = series1 * series2
df_fusion = pd.DataFrame({'liste1': series1.values , 'liste2': series2.values, 'liste3': s3.values})
df_fusion

    liste1  liste2  liste3
0        0      10       0
1        1      11      11
2        2      12      24
3        3      13      39
4        4      14      56
5        5      15      75
6        6      16      96
7        7      17     119
8        8      18     144
9        9      19     171
10      10      20     200
11      11      21     231
12      12      22     264
13      13      23     299

En partant des series1 et series2, faites 2 series qui comportent uniquement les valeurs:
   - presentes dans la series1 et non dans la series2
   - presentes dans la series2 et non dans la series1

In [8]:
series3 = [ item for item in series1 if series1.isin(series2)[item] == False ] 
series3

series4 = [ item for item in series2 if series2.isin(series1)[item-10] == False ] 
series4

series1[-series1.isin(series2)]
series2[-series2.isin(series1)]

4     14
5     15
6     16
7     17
8     18
9     19
10    20
11    21
12    22
13    23
dtype: int64

Faites de même avec la liste3 et la liste4

In [9]:
liste3 = ["de","bd","ng","us","fr","it"]
liste4 = ["fr","cv","ng","us","bs","it"]

liste3series = pd.Series(liste3)
liste4series = pd.Series(liste4)

In [10]:
series5 = [ item for index,item in enumerate(liste3series) if liste3series.isin(liste4series)[index] == False ] 
series5

series6 = [ item for index,item in enumerate(liste4series) if liste4series.isin(liste3series)[index] == False ] 
series6

['cv', 'bs']

### Partie 2

Importer la librairie os et creer une fonction avec en argument le path qui teste si le path existe

In [11]:
import os
path = "PATH/database.csv"
def is_exist(path):
    return os.path.isfile(path)

is_exist(path)

True

A l'aide des methodes propres à pandas faire un dataframe du csv contenu dans le path

In [21]:
df_file = pd.read_csv(path, index_col="Record ID")
df_file

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (16) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,Crime Solved,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
Record ID,,,,,,,,,,,,,,,,,,,,,
1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,Yes,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,Yes,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
3,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,2,Murder or Manslaughter,No,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,0,FBI
4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,Yes,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
5,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,2,Murder or Manslaughter,No,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Unknown,0,1,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638450,WY01500,Park County,Sheriff,Park,Wyoming,2014,January,1,Murder or Manslaughter,No,...,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,Yes,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
638452,WY01701,Sheridan,Municipal Police,Sheridan,Wyoming,2014,September,1,Murder or Manslaughter,Yes,...,Unknown,Female,22,Asian/Pacific Islander,Unknown,Daughter,Suffocation,0,0,FBI
638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,Yes,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI
638454,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2014,September,1,Murder or Manslaughter,Yes,...,Not Hispanic,Female,24,White,Not Hispanic,Daughter,Blunt Object,0,1,FBI

Afficher toutes les colones du dataframe

In [40]:
df_file.columns

Index(['Agency Code', 'Agency Name', 'Agency Type', 'City', 'State', 'Year',
       'Month', 'Incident', 'Crime Type', 'Crime Solved', 'Victim Sex',
       'Victim Age', 'Victim Race', 'Victim Ethnicity', 'Perpetrator Sex',
       'Perpetrator Age', 'Perpetrator Race', 'Perpetrator Ethnicity',
       'Relationship', 'Weapon', 'Victim Count', 'Perpetrator Count',
       'Record Source'],
      dtype='object')

afficher le nombre de lignes du dataframe

In [41]:
df_file.shape[0]

638454

- A l'aide des mask pandas filtrer le dataframe pour afficher voir:  
   - toutes les lignes avec plus d'une victime
   - toutes les lignes avec Perpetrator Sex egale a male
   - le nombre de crime apres les années 2000
   - tout les crime avec plus de 4 victimes commis au mois aout

In [33]:
df_file[df_file["Victim Count"]>1]

,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,Crime Solved,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
Record ID,,,,,,,,,,,,,,,,,,,,,
417104,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2001,April,1,Murder or Manslaughter,Yes,...,Unknown,Male,45,White,Unknown,Acquaintance,Handgun,0,0,FBI
417105,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2001,May,1,Murder or Manslaughter,Yes,...,Unknown,Male,20,Asian/Pacific Islander,Unknown,Acquaintance,Blunt Object,0,0,FBI
417106,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2001,June,1,Murder or Manslaughter,Yes,...,Unknown,Male,20,Asian/Pacific Islander,Unknown,Stranger,Blunt Object,0,1,FBI
417107,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2001,July,1,Murder or Manslaughter,Yes,...,Unknown,Male,23,White,Unknown,Acquaintance,Handgun,0,0,FBI
417108,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2001,July,2,Murder or Manslaughter,No,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638450,WY01500,Park County,Sheriff,Park,Wyoming,2014,January,1,Murder or Manslaughter,No,...,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,Yes,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
638452,WY01701,Sheridan,Municipal Police,Sheridan,Wyoming,2014,September,1,Murder or Manslaughter,Yes,...,Unknown,Female,22,Asian/Pacific Islander,Unknown,Daughter,Suffocation,0,0,FBI
638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,Yes,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI
638454,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2014,September,1,Murder or Manslaughter,Yes,...,Not Hispanic,Female,24,White,Not Hispanic,Daughter,Blunt Object,0,1,FBI

In [32]:
df_file[df_file["Perpetrator Sex"]== 'Male']

,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,Crime Solved,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
Record ID,,,,,,,,,,,,,,,,,,,,,
1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,Yes,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,Yes,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,Yes,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
6,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,May,1,Murder or Manslaughter,Yes,...,Unknown,Male,36,White,Unknown,Acquaintance,Rifle,0,0,FBI
7,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,May,2,Murder or Manslaughter,Yes,...,Unknown,Male,27,Black,Unknown,Wife,Knife,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638447,WY01300,Natrona County,Sheriff,Natrona,Wyoming,2014,September,1,Murder or Manslaughter,Yes,...,Not Hispanic,Male,48,White,Not Hispanic,Mother,Handgun,0,0,FBI
638448,WY01301,Casper,Municipal Police,Natrona,Wyoming,2014,June,1,Murder or Manslaughter,Yes,...,Not Hispanic,Male,22,White,Unknown,Girlfriend,Handgun,0,0,FBI
638449,WY01301,Casper,Municipal Police,Natrona,Wyoming,2014,August,1,Murder or Manslaughter,Yes,...,Unknown,Male,67,Black,Unknown,Friend,Firearm,0,0,FBI
638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,Yes,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,Yes,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI

In [34]:
df_file[df_file["Year"]>2000]

,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,Crime Solved,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
Record ID,,,,,,,,,,,,,,,,,,,,,
417104,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2001,April,1,Murder or Manslaughter,Yes,...,Unknown,Male,45,White,Unknown,Acquaintance,Handgun,0,0,FBI
417105,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2001,May,1,Murder or Manslaughter,Yes,...,Unknown,Male,20,Asian/Pacific Islander,Unknown,Acquaintance,Blunt Object,0,0,FBI
417106,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2001,June,1,Murder or Manslaughter,Yes,...,Unknown,Male,20,Asian/Pacific Islander,Unknown,Stranger,Blunt Object,0,1,FBI
417107,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2001,July,1,Murder or Manslaughter,Yes,...,Unknown,Male,23,White,Unknown,Acquaintance,Handgun,0,0,FBI
417108,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,2001,July,2,Murder or Manslaughter,No,...,Unknown,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638450,WY01500,Park County,Sheriff,Park,Wyoming,2014,January,1,Murder or Manslaughter,No,...,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,Yes,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
638452,WY01701,Sheridan,Municipal Police,Sheridan,Wyoming,2014,September,1,Murder or Manslaughter,Yes,...,Unknown,Female,22,Asian/Pacific Islander,Unknown,Daughter,Suffocation,0,0,FBI
638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,Yes,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI
638454,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2014,September,1,Murder or Manslaughter,Yes,...,Not Hispanic,Female,24,White,Not Hispanic,Daughter,Blunt Object,0,1,FBI

In [37]:
df_file[(df_file["Month"]=="August") & (df_file["Victim Count"]>4)]

,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,Crime Solved,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
Record ID,,,,,,,,,,,,,,,,,,,,,
49047,FL01300,Miami-Dade,County Police,Dade,Florida,1982,August,13,Murder or Manslaughter,Yes,...,Not Hispanic,Male,51,White,Not Hispanic,Unknown,Shotgun,7,0,FBI
49048,FL01300,Miami-Dade,County Police,Dade,Florida,1982,August,13,Murder or Manslaughter,Yes,...,Not Hispanic,Male,51,White,Not Hispanic,Unknown,Shotgun,7,0,FBI
49049,FL01300,Miami-Dade,County Police,Dade,Florida,1982,August,13,Murder or Manslaughter,Yes,...,Not Hispanic,Male,51,White,Not Hispanic,Unknown,Shotgun,7,0,FBI
49050,FL01300,Miami-Dade,County Police,Dade,Florida,1982,August,13,Murder or Manslaughter,Yes,...,Not Hispanic,Male,51,White,Not Hispanic,Unknown,Shotgun,7,0,FBI
49052,FL01300,Miami-Dade,County Police,Dade,Florida,1982,August,13,Murder or Manslaughter,Yes,...,Hispanic,Male,51,White,Not Hispanic,Unknown,Shotgun,7,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623894,WI04110,Oak Creek,Municipal Police,Milwaukee,Wisconsin,2012,August,1,Murder or Manslaughter,Yes,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,5,0,FBI
623895,WI04110,Oak Creek,Municipal Police,Milwaukee,Wisconsin,2012,August,1,Murder or Manslaughter,Yes,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,5,0,FBI
623896,WI04110,Oak Creek,Municipal Police,Milwaukee,Wisconsin,2012,August,1,Murder or Manslaughter,Yes,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,5,0,FBI
623897,WI04110,Oak Creek,Municipal Police,Milwaukee,Wisconsin,2012,August,1,Murder or Manslaughter,Yes,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,5,0,FBI
623898,WI04110,Oak Creek,Municipal Police,Milwaukee,Wisconsin,2012,August,1,Murder or Manslaughter,Yes,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,5,0,FBI